version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: utilize_v2_infra_demo
    ports:
      - "4567-4597:4567-4597"
      - "8080:8080"
    environment:
      - SERVICES=serverless,s3,rds,ecs,ec2,sns,sqs
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"